services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: sdevpoint
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: