services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: sdevpoint
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

#  test_db:
#    image: postgres:17
#    container_name: test_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: qwerty007
#      POSTGRES_DB: sdevpoint
#    volumes:
#      - postgres_test_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    networks:
#      - my_network

volumes:
  postgres_data:
  postgres_test_data:
  redis-data:

networks:
  my_network: