spring:
  application:
    name: sdevpoint
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sdevpoint
    password: qwerty007
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update